ALTERTABLE`tb_exame`ADD`des` VARCHAR( 1000)NULL DEFAULT'' COMMENT'简要',
 ADD`key` VARCHAR( 300)NULL DEFAULT'' COMMENT'关键词',
 ADD`see_num` INT NOTNULL DEFAULT'0' COMMENT'浏览量',
 ADD`idno` VARCHAR( 50)NULL DEFAULT''
 
 ALTERTABLE`tb_class`ADD`objtable` VARCHAR( 50)NULL DEFAULT'' COMMENT'对象表名'